In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [6]:
df = pd.read_csv('/content/hospital_readmissions_30k.csv.xls')

In [ ]:
df.head()

,patient_id,age,gender,blood_pressure,cholesterol,bmi,diabetes,hypertension,medication_count,length_of_stay,discharge_destination,readmitted_30_days
0,1,74,Other,130/72,240,31.5,Yes,No,5,1,Nursing_Facility,Yes
1,2,46,Female,120/92,292,36.3,No,No,4,3,Nursing_Facility,No
2,3,89,Other,135/78,153,30.3,No,Yes,1,1,Home,No
3,4,84,Female,123/80,153,31.5,No,Yes,3,10,Home,No
4,5,32,Other,135/84,205,18.4,No,Yes,6,4,Nursing_Facility,No


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   patient_id             30000 non-null  int64  
 1   age                    30000 non-null  int64  
 2   gender                 30000 non-null  object 
 3   blood_pressure         30000 non-null  object 
 4   cholesterol            30000 non-null  int64  
 5   bmi                    30000 non-null  float64
 6   diabetes               30000 non-null  object 
 7   hypertension           30000 non-null  object 
 8   medication_count       30000 non-null  int64  
 9   length_of_stay         30000 non-null  int64  
 10  discharge_destination  30000 non-null  object 
 11  readmitted_30_days     30000 non-null  object 
dtypes: float64(1), int64(5), object(6)
memory usage: 2.7+ MB


In [ ]:
X = df.drop('readmitted_30_days', axis=1)
y = df['readmitted_30_days']

In [ ]:
df.isnull().sum()

,0
patient_id,0
age,0
gender,0
blood_pressure,0
cholesterol,0
bmi,0
diabetes,0
hypertension,0
medication_count,0
length_of_stay,0


In [ ]:
df[['systolic_bp', 'diastolic_bp']] = df['blood_pressure'].str.split('/', expand=True)

df['systolic_bp'] = pd.to_numeric(df['systolic_bp'])
df['diastolic_bp'] = pd.to_numeric(df['diastolic_bp'])

In [ ]:
df.drop('blood_pressure', axis=1, inplace=True)

In [ ]:
df.drop('patient_id', axis=1, inplace=True)

In [ ]:
df['diabetes'] = df['diabetes'].map({'Yes': 1, 'No': 0})
df['hypertension'] = df['hypertension'].map({'Yes': 1, 'No': 0})
df['readmitted_30_days'] = df['readmitted_30_days'].map({'Yes': 1, 'No': 0})

In [ ]:
pd.get_dummies(df['gender'])

,Female,Male,Other
0,False,False,True
1,True,False,False
2,False,False,True
3,True,False,False
4,False,False,True
...,...,...,...
29995,False,True,False
29996,False,False,True
29997,False,False,True
29998,False,False,True


In [ ]:
df = pd.get_dummies(
    df,
    columns=['gender', 'discharge_destination'],
    drop_first=True
) #now everything is numerical

In [ ]:
X = df.drop('readmitted_30_days', axis=1)
y = df['readmitted_30_days']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=1
)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

logmodel = LogisticRegression()

In [ ]:
logmodel.fit(X_train, y_train)

LogisticRegression()

In [ ]:
predictions = logmodel.predict(X_test)

In [ ]:
logmodel.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
logmodel.predict_proba(X_test)

array([[0.84871819, 0.15128181],
       [0.83782919, 0.16217081],
       [0.89331489, 0.10668511],
       ...,
       [0.91344635, 0.08655365],
       [0.90025793, 0.09974207],
       [0.90791543, 0.09208457]])

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predictions)

array([[7862,    0],
       [1138,    0]])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.87      1.00      0.93      7862
           1       0.00      0.00      0.00      1138

    accuracy                           0.87      9000
   macro avg       0.44      0.50      0.47      9000
weighted avg       0.76      0.87      0.81      9000



/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

Accuracy: 0.8735555555555555
